#!/bin/bash

run_tut() {
  local name=`echo "$1" | sed -e 's/src\///g'`
  erlc $name.erl && erl -noshell -s $name test -s init stop
}

if [ -z $1 ]; then
  echo "Usage: ./run <tut name>"
elif [ $1 = "all" ]; then
  for file in `ls *.erl | cut -d '.' -f 1`; do
    echo "$file ->"
    run_tut $file
  done
else
  if [ -f $1.erl ]; then
    echo "$1 ->"
    run_tut $1
  else
    echo "File $1.erl not found"
  fi
fi

rm -rf *.beam